// Bundles the popup's web fonts: the same faces index.html used to load from
// Google Fonts — Lato 400, Poppins 400 / 600 / 600 italic — latin and
// latin-ext only, as woff2, with each family's SIL Open Font License.
//
//   node scripts/fetch-fonts.mjs
//
// Writes public/fonts/ (the woff2 files and OFL-*.txt, which ship with the
// fonts as the OFL requires) and src/styles/_fonts.scss (their @font-face
// rules, unicode-range and font-display as Google serves them). Needs
// network access; the output is committed and the build never runs this.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Lato&family=Poppins:ital,wght@0,400;0,600;1,600&display=swap';
// Google serves woff2 only to browsers it knows can use it.
const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';
const SUBSETS = ['latin', 'latin-ext'];
const LICENSES = {
  Lato: 'https://raw.githubusercontent.com/google/fonts/main/ofl/lato/OFL.txt',
  Poppins: 'https://raw.githubusercontent.com/google/fonts/main/ofl/poppins/OFL.txt',
};

async function get(url, as = 'text') {
  const response = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return as === 'text' ? response.text() : Buffer.from(await response.arrayBuffer());
}

const css = await get(CSS_URL);
const faces = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{([^}]+)\}/g)]
  .map(([, subset, body]) => ({
    subset,
    family: body.match(/font-family: '([^']+)'/)[1],
    style: body.match(/font-style: (\w+)/)[1],
    weight: body.match(/font-weight: (\d+)/)[1],
    display: body.match(/font-display: (\w+)/)[1],
    url: body.match(/url\((https:[^)]+\.woff2)\)/)[1],
    unicodeRange: body.match(/unicode-range: ([^;]+);/)[1],
  }))
  .filter((face) => SUBSETS.includes(face.subset));

const out = path.join(root, 'public/fonts');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const rules = [];
for (const face of faces) {
  const file = `${face.family.toLowerCase()}-${face.weight}${face.style === 'italic' ? '-italic' : ''}-${face.subset}.woff2`;
  fs.writeFileSync(path.join(out, file), await get(face.url, 'buffer'));
  // Sass comments (//), so no URL reaches the built CSS.
  rules.push(`// ${face.family} ${face.weight}${face.style === 'italic' ? ' italic' : ''}, ${face.subset} — ${face.url}
@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: ${face.display};
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${face.unicodeRange};
}`);
}
for (const [family, url] of Object.entries(LICENSES)) {
  fs.writeFileSync(path.join(out, `OFL-${family}.txt`), await get(url));
}

fs.writeFileSync(
  path.join(root, 'src/styles/_fonts.scss'),
  `// GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
// The faces the popup used to load from ${CSS_URL}
// now ship with it (public/fonts/, SIL Open Font License in OFL-*.txt).
// Same files, same unicode-range and font-display, so text renders as before.

${rules.join('\n\n')}
`
);
console.log(`public/fonts/: ${faces.length} woff2 + ${Object.keys(LICENSES).length} licenses; src/styles/_fonts.scss`);
